gem "bootstrap-sass", "~> 3.2"

gem "puma", :require => false
# gem "haml-rails / slim-rails" meh not sure.. prefer plain ERB
gem 'draper', '~> 1.4.0' # Decorators

gem "rack-mini-profiler", :require => false

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "meta_request"

  # Ruby Style guide metric tool
  gem "rubocop", :require => false

  # CodeClimate free alternative
  # gem "rubycritic"

  # Static analysis tool for checking for security vuln.
  gem 'brakeman', :require => false

  # Rails best practices code metrics tool
  gem "rails_best_practices", :require => false

  # Deployment with capistrano
  gem 'capistrano', '~> 3.1.0'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
  gem 'capistrano-chruby'
end

group :test do
  gem "simplecov", :require => false
  # gem "coveralls" for public code coverage integration -> badge in README

  # Use minitest specs instead of rails testing (on top of minitest unit) or rspec
  gem "minitest-reporters"
  gem "minitest-rails"

  # Integration / Feature / Acceptance Testing
  gem "minitest-rails-capybara"
  gem "capybara-webkit", "~> 1.2"
  gem "launchy"
end
