require 'rake'
require 'rake/testtask'

namespace :test do
  Rake::TestTask.new(:unit) do |t|
    t.libs << "lib" << "bin" << "ext"
    t.test_files = FileList['test/**/*_test.rb']
    t.verbose = true
  end

  Rake::TestTask.new(:spec) do |t|
    t.libs << "lib" << "bin" << "ext"
    t.test_files = FileList['spec/**/*_spec.rb']
    t.verbose = true
  end
end
