require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'

namespace :test do
  Rake::TestTask.new(:unit) do |t|
    t.libs << "test" << "bin" << "ext"
    t.test_files = FileList['test/**/*_test.rb']
    t.verbose = true
  end

  Rake::TestTask.new(:minispec) do |t|
    t.libs << "minispec" << "bin" << "ext"
    t.test_files = FileList['minispec/**/*_spec.rb']
    t.verbose = true
  end

  RSpec::Core::RakeTask.new('spec')
end
