#!/usr/bin/env ruby

if __FILE__ == $0
  $LOAD_PATH.unshift('lib', 'test')
  fast_tests = `find ./test -name *_test.rb -print | xargs grep -l "test_helper"`

  Dir.glob(fast_tests.split("\n")) { |f| require f }
end
