source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0.beta1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.0.beta1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use Rails Html Sanitizer for HTML sanitization
gem 'rails-html-sanitizer', '~> 1.0'

gem "bootstrap-sass", "~> 3.2"

gem "puma", :require => false

gem "draper", "~> 1.4.0"

gem "rack-mini-profiler", :require => false

group :development, :test do
  # Call 'debugger' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exceptions page and /console in development
  # This or better errors?
  gem 'web-console', '~> 2.0.0.beta2'
  # gem "better_errors"
  # gem "binding_of_caller"
  # gem "meta_request"

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Ruby Style guide metric tool
  gem "rubocop", :require => false

  # CodeClimate free alternative
  # gem "rubycritic"

  # Static analysis tool for checking for security vuln.
  gem 'brakeman', :require => false

  # Rails best practices code metrics tool
  gem "rails_best_practices", :require => false

  # Deployment with capistrano
  # gem 'capistrano', '~> 3.1.0'
  # gem 'capistrano-rails', '~> 1.1.0'
  # gem 'capistrano-bundler'
  # gem 'capistrano3-puma'
  # gem 'capistrano-chruby'
end

group :test do
  gem "simplecov", :require => false
  # gem "coveralls" for public code coverage integration -> badge in README
  #
  # Use minitest specs instead of rails testing (on top of minitest unit) or rspec
  gem "minitest-reporters"
  gem "minitest-rails"

  # Integration / Feature / Acceptance Testing
  gem "minitest-rails-capybara"
  gem "capybara-webkit", "~> 1.2"
  gem "launchy"
end

